import { Inter } from "next/font/google";
import "../globals.css";
import { ToastBar, Toaster } from "react-hot-toast";

export const metadata = {
  title: 'Authentication',
  description: 'Generated by Next.js',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-[#F5F5F5]`}>
        {children}
        <Toaster/>
      </body>
    </html>
  )
}

