import { Inter } from "next/font/google";
import "../globals.css";

export const metadata = {
  title: 'Authentication',
  description: 'Generated by Next.js',
}

const inter = Inter({ subsets: ["latin"] });


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter} bg-[#F5F5F5]`}>{children}</body>
    </html>
  )
}

